total_population=int(input())
percentage_of_men=48
total_percentage=100
Number_of_women_in_the_town=total_population*percentage_of_men/total_percentage
result=int(Number_of_women_in_the_town)
print(result)